- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system package
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['ca-certificates', 'curl', 'gnupg', 'lsb-release', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: ADD docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository: 
    repo: deb [arch={{'amd64' if ansible_architecture == 'x86_64' else ansible_architecture}}] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present

- name: Update apt and install docker-ce, docker-ce-cli, containerd.io
  apt: update_cache=yes name={{ item }} state=latest
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Install docker python SDK
  pip:
    name: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ansible_facts['system']}}-{{ansible_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: '+x' 

- name: Install docker python SDK
  pip:
    name: docker-compose
